const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const morgan = require('morgan');
const jwt = require('jsonwebtoken');

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.use(morgan('dev'));

const routes = express.Router();
/** Short example route to generate token  */
routes.post('/', function(req, res) {
    const { body } = req;
    
    const exampleData = {
        name: body.name,
        email: body.email,
    }

    // Used for confirm if the token was generated by server
    const cert = 'private.key';

    // Configure token
    const configToken = {
        expiresIn: '1h',
    }

    // Generate token
    const token = jwt.sign(exampleData, cert, configToken);

    // Response
    res.json({
        success: true,
        message: 'Token created!',
        token: token,
    });
});

app.use('/', routes);

const port = process.env.PORT || 3333;

app.listen(port, function() {
    console.log(`Running in port ${port}`);
});